// src/sys/shell/builtins/app_launch/cmd_q3arena.c — the `q3arena` shell command.
// v38.108 (Q3 phase 8): the same official Quake III Arena game module as `q3vm`
// (qagame.qvm, built from id Software's GPL source by id's own lcc + q3asm,
// executed by id's own QVM interpreter) — but with its level DRAWN. The .bsp the
// module is standing in is textured from the game data on the volume and put on
// screen through TinyGL, with the camera following the module's own
// playerState, and the window's keyboard/mouse input going back in as the
// usercmd that id's Pmove consumes.
//
// Scope, stated plainly because the last time this project drew a window it
// said "Quake III (Mectov)" over a map it had made itself: what this shows is
// id's game code in id's BSP format, rendered by a hand-written renderer, with
// the arena generated by scripts/build_test_bsp.py unless the user staged their
// own map from pak0.pk3. There are no lightmaps, no models, no HUD, no bots.
//
// Same fork-into-kernel-task pattern as `q3`, `q3gl`, `q3play` and `q3vm`: the
// shell's SYS_EXEC_CMD context runs with interrupts disabled, which would
// starve the timer the engine's own clock needs. The dedicated task boots with
// IF=1. Built only with MECTOV_Q3=1.
#include "../../shell_internal.h"

#ifdef MECTOV_Q3
static void q3arena_task_entry(void) {
        extern void q3arena_start(void);
        q3arena_start();   /* never returns (parks in hlt when finished) */
}
#endif

void cmd_q3arena(void) {
#ifdef MECTOV_Q3
        extern int task_fork_kernel(void (*entry)(void), const char* child_arg);
        int pid = task_fork_kernel(q3arena_task_entry, "q3arena");
        if (pid < 0) {
                print("q3arena: failed to fork VM task\n", 0x0C);
                return;
        }
        print("Starting the official qagame VM with its level on screen...\n", 0x0C);
        print("WASD/arrows move, mouse looks, ESC quits. id's own Pmove drives it.\n", 0x07);
#else
        print("q3arena: engine not compiled in (build with MECTOV_Q3=1)\n", 0x0C);
#endif
}
