// src/sys/shell/builtins/app_launch/cmd_q3arena.c — the `q3arena` shell command.
// v38.108 (Q3 phase 8): the same official Quake III Arena game module as `q3vm`
// (qagame.qvm, built from id Software's GPL source by id's own lcc + q3asm,
// executed by id's own QVM interpreter) — but with its level DRAWN. The .bsp the
// module is standing in is textured from the game data on the volume and put on
// screen through TinyGL, with the camera following the module's own
// playerState, and the window's keyboard/mouse input going back in as the
// usercmd that id's Pmove consumes.
//
// v38.111 (retail-map path): `q3arena <name>` loads maps/<name>.bsp from the
// staged game data instead of the generated test arena — the first step of
// "your own pak0's q3dm1 runs here". The name is validated to [a-z0-9_]
// BEFORE it leaves the shell (lowercase qpath, no separators, no escapes), so
// the argument can only ever select among maps/*.bsp on the volume, never open
// anything else. `q3arena` bare keeps the generated arena, which is what every
// regression and CI run asserts on.
//
// Scope, stated plainly because the last time this project drew a window it
// said "Quake III (Mectov)" over a map it had made itself: what this shows is
// id's game code in id's BSP format, rendered by a hand-written renderer, with
// the arena generated by scripts/build_test_bsp.py unless the user staged their
// own map from pak0.pk3. There are no lightmaps, no models, no HUD, no bots.
//
// Same fork-into-kernel-task pattern as `q3`, `q3gl`, `q3play` and `q3vm`: the
// shell's SYS_EXEC_CMD context runs with interrupts disabled, which would
// starve the timer the engine's own clock needs. The dedicated task boots with
// IF=1. Built only with MECTOV_Q3=1.
#include "../../shell_internal.h"

#ifdef MECTOV_Q3
static void q3arena_task_entry(void) {
        extern void q3arena_start(void);
        q3arena_start();   /* never returns (parks in hlt when finished) */
}
#endif

/* v38.149: programmatic launch for the q3menu window (same fork pattern as
 * the shell command below, minus the line parsing). map must be a bare
 * [a-z0-9_] qpath, 1..63 chars — anything else is rejected, so the menu can
 * only ever select among the staged .bsp map files, never open anything
 * else. Returns 0 on fork success, -1 otherwise. Built only with
 * MECTOV_Q3=1. */
int q3arena_launch_map(const char *map) {
#ifdef MECTOV_Q3
        static char child_arg[80];    /* "q3arena " + map + NUL */
        int i = 0;
        if (!map || !map[0]) return -1;
        while (map[i] && i < 63) {
                char ch = map[i];
                if (!((ch >= 'a' && ch <= 'z') ||
                      (ch >= '0' && ch <= '9') || ch == '_')) return -1;
                i++;
        }
        if (!map[i] && i > 0) {
                int k;
                child_arg[0] = 'q'; child_arg[1] = '3'; child_arg[2] = 'a';
                child_arg[3] = 'r'; child_arg[4] = 'e'; child_arg[5] = 'n';
                child_arg[6] = 'a'; child_arg[7] = ' ';
                for (k = 0; k < i; k++) child_arg[8 + k] = map[k];
                child_arg[8 + i] = '\0';
                {
                        extern int task_fork_kernel(void (*entry)(void), const char* child_arg);
                        int pid = task_fork_kernel(q3arena_task_entry, child_arg);
                        if (pid >= 0) return 0;
                }
        }
        return -1;
#else
        (void)map;
        return -1;
#endif
}

void cmd_q3arena(void) {
#ifdef MECTOV_Q3
        /* cmd_b holds the whole command line. v38.119 grammar, after the
         * command word and one space:
         *
         *     [<map>] [fullscreen] [@x,y,z,yaw[,pitch]]
         *
         * The payload is forwarded verbatim (the driver tokenises and
         * re-validates it — this is not a trusted channel), but it is screened
         * here first so a typo reaches the user as "bad argument" instead of a
         * silently different run: every character must be one of
         * [a-z0-9_ @,-], spaces separate tokens and never repeat, and the whole
         * payload must end the line. Anything else means "no argument at all",
         * exactly like the old map-only form. */
        extern char cmd_b[];
        static const char cmd_word[] = "q3arena";
        static char child_arg[128];     /* "q3arena " + payload + NUL */
        int pn = 0, ok = 1;
        const char *s;

        {
                int i = 0;
                while (cmd_word[i] && cmd_b[i] == cmd_word[i]) i++;
                if (cmd_word[i] || (cmd_b[i] != ' ' && cmd_b[i] != '\t')) goto noarg;
                s = cmd_b + i + 1;
                while (*s == ' ' || *s == '\t') s++;
                {
                        int prev_space = 1;     /* leading spaces already eaten */
                        while (s[pn] && pn < 118) {
                                char ch = s[pn];
                                if (ch == ' ') {
                                        if (prev_space) { ok = 0; break; }
                                        prev_space = 1;
                                } else {
                                        if (!((ch >= 'a' && ch <= 'z') ||
                                              (ch >= '0' && ch <= '9') ||
                                              ch == '_' || ch == '@' ||
                                              ch == ',' || ch == '-' ||
                                              ch == '=')) {
                                                ok = 0;
                                                break;
                                        }
                                        prev_space = 0;
                                }
                                pn++;
                        }
                        if (s[pn] != '\0') ok = 0;      /* over-long or rejected */
                        if (ok && prev_space) ok = 0;   /* trailing space */
                }
                if (!ok) {
                        print("q3arena: bad argument (want: [<map>] "
                              "[fullscreen] [nosort] [jump=n] [fire=n] "
                              "[@x,y,z,yaw[,pitch]])\n", 0x0C);
                        goto noarg;
                }
                if (pn == 0) goto noarg;
        }
        {
                /* launch_arg: "q3arena <payload>" — the driver strips the
                 * prefix back off and parses the tokens. task_fork_kernel
                 * copies it before the child can run. */
                int k;
                for (k = 0; cmd_word[k]; k++) child_arg[k] = cmd_word[k];
                child_arg[7] = ' ';
                for (k = 0; k < pn; k++) child_arg[8 + k] = s[k];
                child_arg[8 + pn] = '\0';
                print("Quake III: ", 0x0B);
                print(child_arg + 8, 0x0B);
                print("\n", 0x0B);
                goto fork;
        }
noarg:
        child_arg[0] = 'q'; child_arg[1] = '3'; child_arg[2] = 'a';
        child_arg[3] = 'r'; child_arg[4] = 'e'; child_arg[5] = 'n';
        child_arg[6] = 'a'; child_arg[7] = '\0';
fork:
        {
                extern int task_fork_kernel(void (*entry)(void), const char* child_arg);
                int pid = task_fork_kernel(q3arena_task_entry, child_arg);
                if (pid < 0) {
                        print("q3arena: failed to fork VM task\n", 0x0C);
                        return;
                }
        }
        print("Starting the official qagame VM with its level on screen...\n", 0x0C);
        /* v38.133: the driver runs in a task of its own, so this shell is free
         * — and it is the surface the user is actually looking at, because it
         * is where the command was typed. Poll the driver's own status and
         * print the load as it happens: a terminal that says nothing for two
         * minutes is indistinguishable from a hang, which is exactly what the
         * last report said (and the loading window can be behind this one, or
         * on a host slow enough that its repaints are seconds apart).
         *
         * One line per stage change, a heartbeat every ~5 s while loading,
         * then the game's own line — at which point this returns to the prompt
         * the way it always has, so nothing about the post-launch flow (ESC in
         * the game, then a second `q3arena`, the relaunch path the v38.130
         * proof exercises) changes shape. The 5-minute cap means a driver that
         * never reports cannot hold the shell hostage. */
        {
                extern int q3arena_status(char *buf, int n);
                extern void task_sleep(int);
                static char st[96];
                unsigned waited = 0;
                int last = -1, beats = 0;
                while (waited < 300000u) {
                        int ph = q3arena_status(st, (int)sizeof(st));
                        if (ph != last) {
                                if (ph == 1) {
                                        print("[quake] ", 0x0B);
                                        print(st, 0x07);
                                        print("\n", 0x07);
                                } else if (ph >= 2) {
                                        print("[quake] ", 0x0B);
                                        print(st, 0x0B);
                                        print("\n", 0x0B);
                                }
                                last = ph;
                                beats = 0;
                        } else if (ph == 1 && ++beats >= 5) {
                                print("[quake] ", 0x0B);
                                print(st, 0x07);
                                print("\n", 0x07);
                                beats = 0;
                        }
                        /* In the game, or already over: hand the prompt back
                         * and let the window own the story from here. */
                        if (ph >= 2) break;
                        task_sleep(1000);
                        waited += 1000u;
                }
        }
        print("WASD/arrows move, mouse looks, ESC quits. id's own Pmove drives it.\n", 0x07);
#else
        print("q3arena: engine not compiled in (build with MECTOV_Q3=1)\n", 0x0C);
#endif
}
