#!/usr/bin/env python3
"""Generate src/include/font_aa.h — an antialiased replacement for font8x16.

Same 8x16 cell geometry as the legacy bitmap font, so every consumer (terminal
cell grid, window titles, taskbar, app canvas text) keeps its layout untouched
— only the rendering gets smooth: DejaVu Sans Mono rasterized at 4x
supersampling and box-filtered down to a 4-bit coverage map per pixel, which
the kernel blends with vga_blend_px().

Run from the repo root:  python3 scripts/gen_font.py
"""
import os

from PIL import Image, ImageDraw, ImageFont

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
OUT = os.path.join(ROOT, "src", "include", "font_aa.h")

# Identical geometry to the legacy font8x16: 8 px advance, 16 rows
# (baseline 11 — see note above).
W, H = 8, 16
ADV = 8
SS = 4  # supersample factor

FIRST, LAST = 32, 126  # printable ASCII

FONT_PATH = "/usr/share/fonts/truetype/dejavu/DejaVuSansMono.ttf"# Size 13 is the largest DejaVu Mono size whose ink fits the 8 px cell
# ('#' reaches 9.75 px at 16 — real spill, verified by getbbox). Baseline is
# 11 (not the classic 12): at 13 px this face's ink spans 0.5..14 px above
# the baseline, so 12 would clip descenders at the cell floor. At 13 the
# stems land on fractional pixels (cov 10-11), so we snap near-solid pixels
# to full coverage — the same stem darkening FreeType applies to small
# sizes. Result: solid colour cores, AA edges, everything fits.
BASELINE = 11
FONT_PX = 13
SATURATE_MIN = 10   # cov >= this becomes 15 (solid)


def rasterize():
    font = ImageFont.truetype(FONT_PATH, FONT_PX * SS)
    # wide canvas for the spill check: ink must stay inside the 8 px cell
    wide = W * 3 * SS
    glyphs = {}
    for cp in range(FIRST, LAST + 1):
        img = Image.new("L", (wide, H * SS), 0)
        d = ImageDraw.Draw(img)
        # anchor "ls": left edge x=0, baseline y=BASELINE*SS — no manual
        # ascent math, descenders land where they belong.
        d.text((0, BASELINE * SS), chr(cp), font=font, fill=255, anchor="ls")
        px = img.load()
        # spill check: no ink may exist beyond the cell (it would be clipped
        # silently, corrupting the letterform)
        for y in range(H * SS):
            for x in range(W * SS, wide):
                assert px[x, y] == 0, (
                    f"glyph {cp} '{chr(cp)}' ink spills past the {W}px cell"
                )
        cov = [[0] * W for _ in range(H)]
        max_acc = SS * SS * 255  # every sub-sample fully lit
        for y in range(H):
            for x in range(W):
                acc = 0
                for sy in range(SS):
                    for sx in range(SS):
                        acc += px[x * SS + sx, y * SS + sy]
                cov[y][x] = (acc * 15 + max_acc // 2) // max_acc
        # stem darkening: snap near-solid pixels to full coverage so glyph
        # cores render as exact fg colour (crisp), edges stay gradient
        for y in range(H):
            for x in range(W):
                if cov[y][x] >= SATURATE_MIN:
                    cov[y][x] = 15
        glyphs[cp] = cov
    return glyphs


def emit(glyphs):
    lines = []
    lines.append("#ifndef FONT_AA_H")
    lines.append("#define FONT_AA_H")
    lines.append("")
    lines.append("// Antialiased 8x16 console font (v38.97) — generated by")
    lines.append("// scripts/gen_font.py from DejaVu Sans Mono. DO NOT EDIT BY HAND.")
    lines.append("//")
    lines.append("// Same cell geometry as font8x16 (8 px advance, 16 rows, baseline 11)")
    lines.append("// so all consumers keep their layout. Each pixel is 4-bit coverage")
    lines.append("// (0..15) of glyph ink; blend with vga_blend_px(fg, cov*17).")
    lines.append("// codepoint 32..126 only; anything else renders as a full block")
    lines.append("// (index 95).")
    lines.append("#define FONT_AA_W     8")
    lines.append("#define FONT_AA_CELL_H 16")
    lines.append("#define FONT_AA_ADV   8")
    lines.append(f"#define FONT_AA_BASE   {BASELINE}")
    lines.append("#define FONT_AA_FIRST 32")
    lines.append("#define FONT_AA_LAST  126")
    lines.append("")
    lines.append("// [glyph_index][row][col]; glyph_index = codepoint - 32 for 32..126,")
    lines.append("// index 95 (one past the printable range) is the replacement block.")
    lines.append("static const unsigned char font_aa_data[96][16][8] = {")
    order = list(range(FIRST, LAST + 1)) + [0]  # index 95: replacement block
    for idx, cp in enumerate(order):
        rows = glyphs[cp] if cp in glyphs else [[15] * W for _ in range(H)]
        body = ",\n    ".join(
            "{" + ",".join(str(v) for v in row) + "}" for row in rows
        )
        comma = "," if idx < len(order) - 1 else ""
        label = f"/* '{chr(cp)}' */" if 32 <= cp <= 126 else "/* block */"
        lines.append(f"    {label}")
        lines.append("    {" + body + "}" + comma)
    lines.append("};")
    lines.append("")
    lines.append("#endif // FONT_AA_H")
    return "\n".join(lines) + "\n"


def main():
    glyphs = rasterize()
    # sanity: printable range must have ink somewhere (space is legitimately
    # empty — exempt it), and coverage must never overflow 4 bits
    for cp in range(FIRST, LAST + 1):
        if cp == 32:
            continue
        total = sum(sum(row) for row in glyphs[cp])
        assert total > 0, f"glyph {cp} '{chr(cp)}' rasterized empty"
        assert all(v <= 15 for row in glyphs[cp] for v in row), f"glyph {cp} overflow"
        # crisp-core check: every non-space glyph must own at least one FULL
        # coverage pixel — the whole point of size 16 over 13
        assert any(v == 15 for row in glyphs[cp] for v in row), (
            f"glyph {cp} '{chr(cp)}' has no full-coverage pixel (would look thin)"
        )
    with open(OUT, "w") as f:
        f.write(emit(glyphs))
    print(f"wrote {OUT}, 96 glyphs, cell {W}x{H} adv {ADV} baseline {BASELINE}")


if __name__ == "__main__":
    main()
