#!/usr/bin/env python3
"""Generate apps/lib/tls/tls_roots.h -- the TLS client's trust store.

The store is a plain C array of DER certificates compiled into the binary.
There is no way to add a root at runtime: an OS image that can be talked into
trusting a new CA is worse than one that cannot, so the only way a root enters
is by editing a file and rebuilding.

Usage:
  scripts/gen_tls_roots.py                 # apps/lib/tls/roots/*.pem (default)
  scripts/gen_tls_roots.py --dir /etc/ssl/certs
  scripts/gen_tls_roots.py --bundle /etc/ssl/certs/ca-certificates.crt
  scripts/gen_tls_roots.py --out apps/lib/tls/tls_roots.h

--bundle takes a concatenated PEM file (what Debian calls ca-certificates.crt)
and emits every certificate in it. The --dir form takes one PEM per file, which
is what a curated set in apps/lib/tls/roots/ looks like.

Certificates are emitted as DER. The TLS client's parser is DER-only, and a
store of PEM text would not just fail, it would fail in a way that looks like a
verification bug rather than a formatting one.
"""
import argparse
import base64
import glob
import os
import re
import sys

BANNER = """// apps/lib/tls/tls_roots.h - GENERATED by scripts/gen_tls_roots.py. Do not edit.
//
// The client's entire trust store. Each entry is one DER certificate; the
// verifier walks the chain the server sent and stops at the first entry that
// matches a certificate byte for byte. A certificate's own signature is not
// checked when it is matched here -- that is what being a trust anchor means.
//
// Sources:
%s
//
// Count: %d certificate(s).
"""


def pem_to_der(pem_bytes):
    """Every CERTIFICATE block in `pem_bytes`, decoded to DER."""
    out = []
    text = pem_bytes.decode("ascii", "replace")
    for m in re.finditer(
            r"-----BEGIN CERTIFICATE-----(.*?)-----END CERTIFICATE-----",
            text, re.S):
        b64 = re.sub(r"\s+", "", m.group(1))
        if b64:
            out.append(base64.b64decode(b64))
    return out


def collect(args):
    ders = []
    sources = []
    if args.bundle:
        with open(args.bundle, "rb") as f:
            ders = pem_to_der(f.read())
        sources.append("%s (%d certificates)" % (args.bundle, len(ders)))
    else:
        files = sorted(glob.glob(os.path.join(args.dir, "*.pem")))
        if not files:
            sys.exit("no *.pem in %s -- nothing to generate" % args.dir)
        for p in files:
            with open(p, "rb") as f:
                found = pem_to_der(f.read())
            if not found:
                print("warning: %s has no CERTIFICATE block, skipping" % p,
                      file=sys.stderr)
                continue
            ders.extend(found)
            sources.append("%s (%d)" % (p, len(found)))
    if not ders:
        sys.exit("no certificates found")
    return ders, sources


def main():
    here = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
    ap = argparse.ArgumentParser()
    ap.add_argument("--dir", default=os.path.join(here, "apps", "lib", "tls", "roots"))
    ap.add_argument("--bundle", help="a single concatenated PEM file")
    ap.add_argument("--out", default=os.path.join(here, "apps", "lib", "tls", "tls_roots.h"))
    args = ap.parse_args()

    ders, sources = collect(args)

    out = [BANNER % ("\n".join("//   " + s for s in sources), len(ders))]
    out.append("#ifndef MCT_TLS_ROOTS_H\n#define MCT_TLS_ROOTS_H\n\n")
    out.append('#include "src/include/types.h"\n\n')
    for i, d in enumerate(ders):
        body = ", ".join("0x%02x" % b for b in d)
        out.append("static const uint8_t tls_root_%d[%d] = {\n    %s\n};\n"
                   % (i, len(d), body))
    out.append("\nconst tls_root_t tls_roots[] = {\n")
    for i, d in enumerate(ders):
        out.append("    { tls_root_%d, %d },\n" % (i, len(d)))
    out.append("};\n")
    out.append("const int tls_roots_count = %d;\n" % len(ders))
    out.append("\n#endif // MCT_TLS_ROOTS_H\n")

    with open(args.out, "w") as f:
        f.write("".join(out))
    print("wrote %s: %d certificates, %d bytes"
          % (args.out, len(ders), os.path.getsize(args.out)))


if __name__ == "__main__":
    main()